apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-todo
  namespace: project
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: create-todo
              image: maxim/cron:latest
              imagePullPolicy: IfNotPresent
              env:
                - name: API_URL
                  value: "http://todo-backend-svc:3001"
          restartPolicy: OnFailure
