apiVersion: apps/v1
kind: Deployment
metadata:
  name: golog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
        - name: golog
          image: maxim/golog:latest
          imagePullPolicy: IfNotPresent
