apiVersion: apps/v1
kind: Deployment
metadata:
  name: golog-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golog
  template:
    metadata:
      labels:
        app: golog
    spec:
      containers:
        - name: golog
          image: maxim/golog:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
