apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: project
data:
  POSTGRES_USER: ENC[AES256_GCM,data:y4djPGcMdKoYsTY8,iv:QpzKYho8ZFwZL4kUNo+oTq4GUTPYic8+Fg9lYLurv2I=,tag:MsgfmaW0Q+nUeNOyl6rrug==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:K/xfRA1ZptXR3pluqWhcTA==,iv:p4vdb2RJs+40D3KqLRAaNIkLrDw6Qo5Yv1HGlaVaGvg=,tag:zHS9feJcFtUvFOhlzboSyQ==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:Ak5hjGhIMAJ+fbXb,iv:ZHID4qLQSBJ3iRKW5SYoR4BWSsx5xH/q2ShmQpsrFCE=,tag:9p70xSlEAdkOzWFQe+HcjA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1xcgx0kpsgyv23za0cvfsy42cj8wrg06fnwu5la054ffmenklpcgqwhxylz
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBockFnVHFXK0dNSHVhbW1v
        YWp5MUNUZkIySHJzUHA2RXA3bi9LQ1FJcnpVCmJLSGY4WWNUbkJ4UVNINCtTeVFC
        cFU4MDBCc0Z4bDlYdmpVWFhtV2tDekUKLS0tIFdmUEgyaGJ1LzY3bVQvVS9ocDYz
        RWwvWmNHSE1qT2sybjNteHVlYTZhR1UKNfvZtfgrhtdCfpw+PCLrwM1ltIDr3zBZ
        3nG7oa6Mc+HKIjeInkopeS9qdfOrIFRIdLfDelpQUAHfOLQRWYXz5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-07T21:50:40Z"
  mac: ENC[AES256_GCM,data:rl6Fqlq3i8QvSM1EQl3zjNaxdxyiJmeTQxmOruK6kdrIH/uBqyE/hFAeA2Ne4ytyi5Kexam7W0XbSL/Rnl8Cyl71LjyIHfPi6BEg9uvghn5rtFk8EL0Fke/gVl58b32Mj2GGUaO7l15ZHAbSJ6IFwAvP8jz4dJvEKGRYfS8hV6Q=,iv:KxVoadoaOuck7XUgsDpWW3hJo7HHmUkGJmr0YrxymYI=,tag:43629WPC5czuyzNlY9eY9g==,type:str]
  pgp: []
  encrypted_regex: ^(data)$
  version: 3.9.2
