apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: persisted-volume
          persistentVolumeClaim:
            claimName: persisted-claim
      containers:
        - name: backend
          image: maxim/todo-backend:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: persisted-volume
              mountPath: /usr/src/app/cache
        - name: frontend
          image: maxim/todo-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
