apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopong
  namespace: dwk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gopong
  template:
    metadata:
      labels:
        app: gopong
    spec:
      containers:
        - name: gopong
          image: maxim/gopong:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_HOST
              value: "postgres-svc"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
